version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"  # RTSP 포트
    restart: unless-stopped

  streamer:
    build: .
    container_name: stream_worker
    restart: unless-stopped
    depends_on:
      - mediamtx
